reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

reee.js
Adds JavaScript implementation.
=> Adds JavaScript Implementation of ree

reee.lua
High-performance REEEEEEEEEEEEEEE
=> Lua(JIT) REEEEEEE

reee.rs
This pull reeeeeeeeequest adds a Rust implementation of reeeeeee.
=> Add Rust implementation

ree.bas, reee.d
Added an DLang implementation, runnable with `rdmd reee.d`
As well, i added an Q/FreeBasic version, load it in QBasic or compile with `fbc reee.bas`
=> Added D and Q/FreeBasic implementation

reee.scm
Couldn't quite figure out Scheme generators so .... ¯\_(ツ)_/¯
=> Added Scheme implementation

reee.scala
=> Added Scala implementation

reee.fsx
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE …
=> F# implementation

reee.vbs
Tested on cscript Microsoft (R) Windows Script Host Version 5.812
=> Creeeate reee.vbs

reee.bat
=> Creeeate reee.bat

reee.ino
=> Adding Arduino implementation

reee.vb
=> Added debug and trace output

reee.rml
=> REEEEEEEEEEEEEML implementation

reee.hs
=> Created reee.hs

reee.hx
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
=> Adding Haxe Implementation

reeelogo
reeeeeeeeeeee
https://www.calormen.com/jslogo/
=> Added turtle instructions for logo Interpreter

reee.zig
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
=> Added zig implementation

reee.dart
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
=> Added dart implementation

reee.mjs
Because why not? 
https://medium.com/passpill-project/files-with-mjs-extension-for-javascript-modules-ced195d7c84a
=> Duplicate `reee.js` to `reee.mjs`

reee.spl
How to run:
```
wget https://treskal.com/s/spl-121tar.gz
tar -xf spl-121tar.gz
cd spl-1.2.1
make 2>/dev/null
spl/bin/spl2c < reee.spl > reee.c
gcc reee.c -Ispl/include/ spl/lib/libspl.a -lm -o reee
./reee
```
=> Added Shakespeare Programming Language support.

reee.sql
Implemented as stored procedure in MySQL 5.7
=> MySQL implementation

reee.pas
Only the initial program "begin" can be "end"-ed with a ´.´
=> Fix building for Pascal

reee.cmd
=> Added reee.cmd

reee.red
=> Add .red support

reee.ook
=> added Ook!

reee.lisp
=> add lisp implementation

reee.el
An Emacs Lisp implementation. 
P.S. We have something called the "long-lines issue" in Emacs. I know the newlines break the pattern a bit but they are to prevent that.
=> Adhoc | Create reee.el.

reee.linux.asm
eEEeeeeEeeeeeEeeeEEeeeEEeeeEEeeeEeeeEEeee
(Seriously speaking, now the assembly one will output infinite Es instead of just 'reee')
=> eeeeeeeeeEEEeeEEeeEEeeeEEeeeEEeeeEeeeEE in linuks asm

reee.rkt
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
=> REEEEEEEEEEEE: Add racket implementation

reee.rexx
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
=> Rexx implementation.

reee.js
console.log inserts a \n, however process.stdout.write doesn't producing `reeeee` not 
```
r
e
e
e
e
```
=> Improve JSRee

reee.rct
Lol ReCT is unknown but needed.
(For more info: https://github.com/RedcubeDev-ByteSpace/ReCT)
=> Added ReCT support aswell

reee.coffee
@ScottMansfield can you look at this?
=> reee.coffee
